on:
  push:
    branches: [ main ]
 # pull_request:
 #   branches: [ main ]


jobs:
  
  container-job:
    runs-on: ubuntu-latest
    container: docker:19.03
    #services: 
    #   docker:19.03-dind

  #- name:Build and Deploy for NPCI Dev in AWS: 
  build:
    runs-on: ubuntu-latest
    needs: [container-job]
    steps:
      - run: echo "build 2 completed"

    if: contains( github.ref, 'main')
    
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "build 2 completed"

    if: contains( github.ref, 'main') 
