container: docker:19.03

services: 
  - docker:19.03-dind

jobs:
  #- name: Build for Dev server in GCP
  build:
    runs-on: ubuntu-latest
    steps:
      - echo "build 1 completed"

    if: contains( github.ref, 'master')


  #- name:Build and Deploy for NPCI Dev in AWS: 
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - echo "build 2 completed"

    if: contains( github.ref, 'master')
