on:
  push:
    branches: [ main ]
 # pull_request:
 #   branches: [ main ]


jobs:

  container-job:
   
    name: run a container
    runs-on: ubuntu-latest
    container: docker:19.03
    services:
      # Label used to access the service container
      docker:
        # Docker Hub image
        image: docker:19.03-dind
    steps:
    - name: docker 
      run: |
           docker pull nginx
           
  build: 
  
    name: Build for Dev server in AWS
    runs-on: ubuntu-latest
    container: docker:19.03
    services:
      # Label used to access the service container
      docker:
        # Docker Hub image
        image: docker:19.03-dind
    needs: [container-job]
    steps:
      - name: Test for environment vairable
        run: |
             echo "build ${{secrets.NAME_VAR}} completed"
             echo "build 3 completed"
             docker pull nginx
            
    if: contains( github.ref, 'main')
    
  build-and-deploy:
  
    name: Deploy for Dev server in AWS
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "build 2 completed"
    if: contains( github.ref, 'main') 
